[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "zlib",
  "zlib.dev",
  "libjpeg",
  "libjpeg.dev",
  "libpng",
  "libpng.dev",
  "libtiff",
  "libtiff.dev",
  "freetype",
  "freetype.dev"
]